Update to version DNG SDK 1.5 Jamaika1/dng_sdk_1.5.1_-_gpr_sdk_1.0.0@756dd48
```
negativeProcessor.cpp: In constructor 'NegativeProcessor::NegativeProcessor(AutoPtr<dng_host>&, LibRaw*, Exiv2::Image::UniquePtr&)':
negativeProcessor.cpp:121:49: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = Exiv2::Image; _Dp = std::default_delete<Exiv2::Image>]'
  121 |                                      m_host(host) {
      |                                                 ^
In file included from c:\msys1021\include\c++\10.2.1\memory:83,
                 from c:\msys1021\x86_64-w64-mingw32\include\exiv2\basicio.hpp:30,
                 from c:\msys1021\x86_64-w64-mingw32\include\exiv2\image.hpp:27,
                 from negativeProcessor.h:24,
                 from negativeProcessor.cpp:23:
c:\msys1021\include\c++\10.2.1\bits\unique_ptr.h:468:7: note: declared here
  468 |       unique_ptr(const unique_ptr&) = delete;
      |       ^~~~~~~~~~
```